name = "broker-proxy-worker"
main = "worker.js"
compatibility_date = "2025-08-22"

[vars]
CACHE_VERSION = "23"

routes = [
  "astro.theqalink.com/*"
]

[[d1_databases]]
binding = "DB"
database_name = "broker-sorting-db"
database_id = "ba34ff09-69bb-4c57-989b-92f07aa8015a"