name = "broker-proxy-worker"
main = "worker.js"
compatibility_date = "2025-08-22"

[[d1_databases]]
binding = "DB"
database_name = "broker-sorting-db"
database_id = "0e441d59-b7d3-4715-add4-01f07bf315c5"