name = "broker-proxy-worker"
main = "worker.js"
compatibility_date = "2025-09-04"

[vars]
PURGE_TOKEN = "dfdf76dfdfyuh343kfd63hje3"
CACHE_TTL = 3600
BROKER_CACHE_TTL = 300
MAX_BROKERS_PER_COUNTRY = 6
ENVIRONMENT = "production"

routes = [
  "astro.theqalink.com/*"
]

[[d1_databases]]
binding = "DB"
database_name = "broker-sorting-db"
database_id = "ba34ff09-69bb-4c57-989b-92f07aa8015a"

[[kv_namespaces]]
binding = "CACHE"
id = "a6271f83f7fe4090ab82f3aea1c080fa"

# Cron triggers for automatic cache warming every 6 hours
[triggers]
crons = ["0 */6 * * *"]

# Environment-specific configurations
[env.production.vars]
CACHE_TTL = 7200
BROKER_CACHE_TTL = 3600
DEBUG = false

[env.staging.vars]
CACHE_TTL = 900
BROKER_CACHE_TTL = 600
DEBUG = true